#ifndef WORLDCONSTANTS_HPP_INCLUDED
#define WORLDCONSTANTS_HPP_INCLUDED

	#define WORLD_SIZE 32
	#define WORLD_HEIGHT 256

	#define CHUNK_SIZE 16
	#define CHUNK_HEIGHT 256
	
	#define	SECTION_SIZE 8
	
# endif // WORLDCONSTANTS_HPP_INCLUDED
