version: 0.1.{build}

only_commits:
  message: /\[build\]/

skip_branch_with_pr: true

image: Visual Studio 2017

platform: x64
configuration:
  - Debug
  - Release

before_build: 
  - cmd: c:\projects\gl-craft\vendor\bin\premake\premake5.exe vs2017

for:
  -
    matrix:
      only:
        - configuration: Release

    after_build:
      - cmd: 7z a gl-craft.zip c:\projects\gl-craft\gl-craft\Res
      - cmd: 7z a gl-craft.zip c:\projects\gl-craft\bin\Release-windows-x86_64\gl-craft\gl-craft.exe

    artifacts:
        - path: gl-craft.zip
          name: gl-craft

    deploy:
      description: 'GitHub release'
      provider: GitHub
      auth_token:
        secure: A/tcgrplDHPdwJjG+ONMx7hcoM15nTzNZ3SNAdYAQFGE1F0KAt1ZwBe4X9fzZlzb
      artifact: gl-craft